package csvregistry

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// generatedPath is the frontend file this package emits. It is committed, and
// this test fails when it is stale, so the ordinary `go test` in verify.mjs is
// what catches drift - no extra tooling, no generate step anyone can skip.
var (
	frontendDir   = filepath.Join("..", "..", "..", "frontend")
	generatedPath = filepath.Join(frontendDir, "src", "generated", "csv-columns.ts")
)

// The dev container bind-mounts ./backend to /app and nothing else, so the
// frontend tree genuinely is not there. That has to be distinguishable from the
// file being stale or deleted, or this test reports a drift that does not exist
// every time it runs in the container - which is the runner /ship and verify.mjs
// both prefer.
//
// The distinction is the directory, not the file. No frontend/ at all means a
// backend-only checkout. A frontend/ with the generated file missing from it is
// a real failure, and is reported as one.
func frontendTreePresent() bool {
	info, err := os.Stat(frontendDir)
	return err == nil && info.IsDir()
}

// A .ts file rather than .json because the frontend tsconfig does not enable
// resolveJsonModule, and emitting TypeScript also hands the picker real types
// instead of `any`.
func render() (string, error) {
	var b strings.Builder

	b.WriteString(`// Code generated by backend/internal/csvregistry. DO NOT EDIT.
//
// Regenerate with:  cd backend && go test ./internal/csvregistry -update
//
// This is the single source of which columns each CSV export emits, and in what
// order. It used to be retyped by hand in every export dialog with a comment
// asking the next person to keep it in sync; contracts drifted two columns that
// way and shipped a file with headers the picker had never offered.
//
// Labels are deliberately NOT here. "Assigned To" and "Kit #" are UI copy and
// belong beside the components that render them, in csv-labels.ts.

export interface CsvColumn {
  key: string;
  /** Fallback label. The frontend prefers its own copy in csv-labels.ts. */
  label: string;
  /** A blank cell is a row error, and the template always carries it. */
  required: boolean;
  /** False means server-owned: never in a template, never read on import. */
  templatable: boolean;
  /** Template comment line for this column, when it has one. */
  note?: string;
}

export interface CsvDomainColumns {
  resource: string;
  columns: CsvColumn[];
  /** False for an export-only domain, which therefore has no template either. */
  import: boolean;
}

export const CSV_COLUMNS: CsvDomainColumns[] = [
`)

	for _, d := range All() {
		fmt.Fprintf(&b, "  {\n    resource: %s,\n    import: %t,\n    columns: [\n", ts(d.Resource), d.Import)
		for _, c := range d.Columns {
			fmt.Fprintf(&b, "      { key: %s, label: %s, required: %t, templatable: %t",
				ts(c.Key), ts(c.Label), c.Required, c.Templatable)
			if c.Note != "" {
				fmt.Fprintf(&b, ", note: %s", ts(c.Note))
			}
			b.WriteString(" },\n")
		}
		b.WriteString("    ],\n  },\n")
	}
	b.WriteString("];\n")
	return b.String(), nil
}

func TestGeneratedColumnsAreCurrent(t *testing.T) {
	want, err := render()
	if err != nil {
		t.Fatalf("render: %v", err)
	}

	if !frontendTreePresent() {
		// Not a pass. CI checks out the whole repo and runs this for real, and so
		// does verify.mjs when it falls back to the host toolchain. Saying which
		// matters: a skip nobody can account for is how a check stops running.
		t.Skip("no frontend/ in this checkout (backend-only container mount); " +
			"CI and the host toolchain run this check against the real tree")
	}

	if *update {
		if err := os.MkdirAll(filepath.Dir(generatedPath), 0o750); err != nil {
			t.Fatalf("creating generated dir: %v", err)
		}
		if err := os.WriteFile(generatedPath, []byte(want), 0o600); err != nil {
			t.Fatalf("writing %s: %v", generatedPath, err)
		}
		t.Logf("wrote %s", generatedPath)
		return
	}

	got, err := os.ReadFile(generatedPath) // #nosec G304 -- path is a package constant
	if err != nil {
		t.Fatalf("reading %s: %v\n\nRun `go test ./internal/csvregistry -update` to create it.", generatedPath, err)
	}
	if string(got) == want {
		return
	}
	t.Errorf(
		"%s is stale.\n\nA CSV column list changed and the frontend copy did not follow.\n"+
			"Regenerate it in the same commit:\n\n  cd backend && go test ./internal/csvregistry -update\n",
		generatedPath)
}

// Every domain that has an export must be in the registry, or its picker has
// nothing to render. This is the check that notices a new domain was wired up
// and never added here.
func TestEveryRegisteredDomainHasColumns(t *testing.T) {
	seen := map[string]bool{}
	for _, d := range All() {
		if d.Resource == "" {
			t.Error("a domain has no resource name")
		}
		if seen[d.Resource] {
			t.Errorf("duplicate resource %q", d.Resource)
		}
		seen[d.Resource] = true

		if len(d.Columns) == 0 {
			t.Errorf("%s has no columns", d.Resource)
		}
		for _, c := range d.Columns {
			if c.Key == "" || c.Label == "" {
				t.Errorf("%s has a column with an empty key or label: %+v", d.Resource, c)
			}
		}
		// An importable domain needs at least one column a person can fill in,
		// otherwise its template would be empty.
		if d.Import {
			any := false
			for _, c := range d.Columns {
				if c.Templatable {
					any = true
					break
				}
			}
			if !any {
				t.Errorf("%s declares import but has no templatable column", d.Resource)
			}
		}
	}
}

// update shares the -update flag name with csvtabletest so one invocation
// refreshes every generated artefact in the tree.
var update = flag.Bool("update", false, "rewrite the generated frontend column manifest")

// ts renders a TypeScript single-quoted string. Go's %q emits double quotes and
// the frontend lints for single, so a generated file using %q fails the very
// check it has to pass to be committed.
func ts(v string) string {
	escaped := strings.ReplaceAll(v, "\\", "\\\\")
	escaped = strings.ReplaceAll(escaped, "'", "\\'")
	return "'" + escaped + "'"
}
