package satcomservice

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

type Repository interface {
	FindAll(ctx context.Context) ([]*SatcomService, error)
	FindByID(ctx context.Context, id string) (*SatcomService, error)
	AbbrevExists(ctx context.Context, abbrev string) (bool, error)
	AbbrevExistsExcluding(ctx context.Context, abbrev, excludeID string) (bool, error)
	Create(ctx context.Context, s *SatcomService) error
	Update(ctx context.Context, s *SatcomService) error
	Delete(ctx context.Context, id string) error
}

type PostgresRepository struct {
	db *pgxpool.Pool
}

func NewRepository(db *pgxpool.Pool) Repository {
	return &PostgresRepository{db: db}
}

const selectCols = `id, abbrev, name, description, created_by, updated_by, created_at, updated_at`

func (r *PostgresRepository) scan(row pgx.Row) (*SatcomService, error) {
	s := &SatcomService{}
	err := row.Scan(
		&s.ID, &s.Abbrev, &s.Name, &s.Description,
		&s.CreatedBy, &s.UpdatedBy, &s.CreatedAt, &s.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	return s, nil
}

func (r *PostgresRepository) FindAll(ctx context.Context) ([]*SatcomService, error) {
	rows, err := r.db.Query(ctx,
		`SELECT `+selectCols+` FROM services ORDER BY lower(abbrev) COLLATE natural_sort ASC`,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []*SatcomService
	for rows.Next() {
		s, err := r.scan(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, s)
	}
	return items, rows.Err()
}

func (r *PostgresRepository) FindByID(ctx context.Context, id string) (*SatcomService, error) {
	row := r.db.QueryRow(ctx,
		`SELECT `+selectCols+` FROM services WHERE id = $1`, id,
	)
	s, err := r.scan(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrServiceNotFound
		}
		return nil, err
	}
	return s, nil
}

func (r *PostgresRepository) AbbrevExists(ctx context.Context, abbrev string) (bool, error) {
	var exists bool
	err := r.db.QueryRow(ctx,
		`SELECT EXISTS(SELECT 1 FROM services WHERE lower(abbrev) = lower($1))`, abbrev,
	).Scan(&exists)
	return exists, err
}

func (r *PostgresRepository) AbbrevExistsExcluding(ctx context.Context, abbrev, excludeID string) (bool, error) {
	var exists bool
	err := r.db.QueryRow(ctx,
		`SELECT EXISTS(SELECT 1 FROM services WHERE lower(abbrev) = lower($1) AND id != $2)`,
		abbrev, excludeID,
	).Scan(&exists)
	return exists, err
}

// Create fills in s.ID from the row it just wrote. The id is generated by the
// database rather than in Go, so RETURNING is what carries it back -- the
// alternative, re-reading the table and matching on abbrev, costs a full scan
// and has no answer for the case where the match fails.
func (r *PostgresRepository) Create(ctx context.Context, s *SatcomService) error {
	err := r.db.QueryRow(ctx,
		`INSERT INTO services (id, abbrev, name, description, created_by, updated_by, created_at, updated_at)
		 VALUES (gen_random_uuid()::text, $1, $2, $3, $4, $5, $6, $7)
		 RETURNING id`,
		s.Abbrev, s.Name, s.Description,
		s.CreatedBy, s.UpdatedBy, s.CreatedAt, s.UpdatedAt,
	).Scan(&s.ID)
	return mapUniqueViolation(err)
}

func (r *PostgresRepository) Update(ctx context.Context, s *SatcomService) error {
	_, err := r.db.Exec(ctx,
		`UPDATE services SET abbrev=$1, name=$2, description=$3, updated_by=$4, updated_at=$5
		 WHERE id=$6`,
		s.Abbrev, s.Name, s.Description, s.UpdatedBy, s.UpdatedAt, s.ID,
	)
	return mapUniqueViolation(err)
}

func (r *PostgresRepository) Delete(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx, `DELETE FROM services WHERE id = $1`, id)
	return err
}

// mapUniqueViolation turns the services_abbrev_lower_idx constraint into a
// domain error. The service checks for a duplicate abbrev first; this closes the
// race where two concurrent writes both pass that check, which otherwise
// surfaced as a 500 for what is really a 409.
func mapUniqueViolation(err error) error {
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) && pgErr.Code == "23505" {
		return ErrServiceAbbrevExists
	}
	return err
}
